const companies = [
['Tajhayzat Alnukhba Branch O.','General Traiding, Contracting','ALI YOUSIF YASEEN','گوندی ئیتاڵی 1 -','07507441111','15/09/2026','31/12/2026','2020467470'],
['ZUMRA CO.','General Traiding, Training','GULAN HAWAR WALI','ناوەندی هەولێر - گوندی ئینگلیزی','','15/09/2026','31/12/2027','2020467469'],
['SRWSHTI KHORHALAT CO.','General Traiding, electrical tools','','هەولێر','','','','2020467433'],['LIFE BALANCE CO.','Investment','','هەولێر','','','','2020467426'],['SANAD ALMUSTAKBAL CO.','General Traiding','','هەولێر','','','','2020467408'],['BILAD ALMAHAR CO.','General Traiding','','هەولێر','','','','2020467404'],['RE HEZ CO.','General Traiding','','هەولێر','','','','2020467392'],['PARTNER STUDIO DESIGN CO.','Engineering','','هەولێر','','','','2020467384'],['ALSUNBULA ALHAJINA','agricultural products','','هەولێر','','','','2020467375'],['FATIMA CO.','Import & Export','','هەولێر','','','','2020467373'],['AFAQ ALMAJD CO.','General Traiding','','هەولێر','','','','2020467369'],['ORIOLES TANDURUSTY CO.','General Traiding','','هەولێر','','','','2020467367'],['KARZHEEN CO.','General Traiding, Electronic, Energy','','هەولێر','','','','2020467364'],['Mustaqbal Alghad','Services, transfer','','هەولێر','','','','2020467352'],['THREE B CO.','Investment','','هەولێر','','','','2020467347'],['ROJ CO.','Contracting','','هەولێر','','','','2020467348'],['BUSINESS WAVE SOLUTION CO.','telecommunication','','هەولێر','','','','2020467333'],['KHABIR AL MAMLAKE','General Traiding, foodstuffs','','هەولێر','','','','2020467329'],['Ghur Alhandasia CO.','General Traiding','','هەولێر','','','','2020467319'],['ALKAHRORAQAMIA CO.','Services','','هەولێر','','','','2020467295'],['Jathabiyat Aljamal co.','Beauty tools','','هەولێر','','','','2020467294'],['SHKO CO.','Contracting','','هەولێر','','','','2020467291'],['LASK CO.','General Traiding','','هەولێر','','','','2020467289'],['RUYAT ALMASAR CO.','General Traiding','','هەولێر','','','','2020467281']
].map(([name,activity,manager,location,phone,membership,end,id])=>({name,activity,manager,location,phone,membership,end,id,email:''}));
const $=s=>document.querySelector(s), grid=$('#grid'), dialog=$('#detail');
function render(items=companies){$('#count').textContent=`${items.length} کۆمپانیا پیشان دەدرێت`;grid.innerHTML=items.map(c=>`<article class="card"><span class="badge">ACTIVE MEMBER</span><div class="globe">◎</div><h2>${c.name}</h2><p>${c.activity}</p><button class="more" data-id="${c.id}">زیاتر</button></article>`).join('');document.querySelectorAll('.more').forEach(b=>b.onclick=()=>show(companies.find(c=>c.id===b.dataset.id)))}
function value(v){return v||'—'}
function show(c){$('#detailBody').innerHTML=`<div class="detail-wrap"><div class="detail-head"><div class="avatar">◎</div><div><h2>${c.name}</h2><p>${c.activity}</p></div><span class="status">ACTIVE MEMBER</span></div><div class="info"><div class="field"><b>MANAGER</b><span>${value(c.manager)}</span></div><div class="field"><b>LOCATION</b><span>${value(c.location)}</span></div><div class="field"><b>PHONE</b><span>${value(c.phone)}</span></div><div class="field"><b>EMAIL</b><span>${value(c.email)}</span></div><div class="field"><b>MEMBERSHIP</b><span>${value(c.membership)}</span></div><div class="field"><b>END DATE</b><span>${value(c.end)}</span></div><div class="field"><b>CATEGORY</b><span>Company</span></div></div><section class="activities"><h3>ACTIVITIES</h3><div class="chips">${c.activity.split(',').map(x=>`<span class="chip">${x.trim()}</span>`).join('')}</div></section><div class="detail-actions"><button class="map" id="map">⌖ کردنەوە لە Maps</button><button class="copy" id="copy">⧉ کۆپی‌کردنی زانیاری</button><a class="copy" target="_blank" href="https://www.erbilchamber.org/companiesDetail.aspx?id=${c.id}">سەرچاوەی فەرمی ↗</a></div></div>`;dialog.showModal();$('#map').onclick=()=>window.open('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(c.location||c.name+' Erbil'),'_blank');$('#copy').onclick=()=>copy(`${c.name}\nManager: ${c.manager}\nLocation: ${c.location}\nPhone: ${c.phone}\nActivities: ${c.activity}`)}
function copy(text){navigator.clipboard.writeText(text);const t=$('#toast');t.textContent='زانیارییەکان کۆپی کران';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
$('#search').oninput=e=>{let q=e.target.value.toLowerCase();render(companies.filter(c=>(c.name+c.activity+c.manager+c.location).toLowerCase().includes(q)))};$('.close').onclick=()=>dialog.close();
$('#copyAll').onclick=()=>copy(companies.map(c=>`${c.name} | ${c.activity} | ${c.manager} | ${c.location} | ${c.phone}`).join('\n'));
$('#export').onclick=()=>{const rows=[['Company','Activities','Manager','Location','Phone','Email','Membership','End Date'],...companies.map(c=>[c.name,c.activity,c.manager,c.location,c.phone,c.email,c.membership,c.end])];const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v||'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='erbil-chamber-companies.csv';a.click();URL.revokeObjectURL(a.href)};
render();
